repos:
-   repo: local
    hooks:
    - id: fmt
      name: fmt
      description: Format files with cargo fmt.
      entry: cargo fmt
      language: system
      types: [rust]
      args: ["--"]
    - id: cargo-check
      name: cargo check
      description: Check the package for errors.
      entry: make check
      language: system
      types: [rust]
      pass_filenames: false
    - id: cargo-clippy
      name: cargo clippy
      description: Run the clippy linter.
      entry: make lint
      language: system
      types: [rust]
      pass_filenames: false
